"""
Phase 0 baseline — measure the PaddleOCR pipeline end-to-end on a realistic
scanned-notes fixture, broken down by stage. Goal: a number to beat with PyO3.

Stages timed:
  1. PDF rasterize (pymupdf)
  2. Preprocess (denoise + binarize via PIL)
  3. PaddleOCR inference (text detection + recognition)
  4. Result stitching (boxes -> reading order -> plain text)

Output: one row of CSV per page, plus a summary.

The fixture is generated by ocr_phase0_fixture.py — it embeds each page as a
200-DPI JPEG-style image, so when we re-rasterize we MUST use a 1:1 zoom
(target_dpi = source_dpi) or the source gets 4x upsampled. For a 200 DPI
fixture, target_dpi=200 → ~1654x2339 px/page (~4 MP).
"""
import argparse
import csv
import sys
import time
from pathlib import Path

import numpy as np
from PIL import Image, ImageFilter, ImageOps

import fitz  # pymupdf

DPI = 200


def rasterize(pdf_bytes: bytes, dpi: int = 200) -> list[Image.Image]:
    """Rasterize PDF pages. `dpi` here is the EFFECTIVE rasterization DPI; for a
    200-DPI scanned fixture, dpi=200 → ~1654x2339 px/page (1:1 zoom). For a
    72-DPI text PDF you'd use dpi=200 to upscale."""
    doc = fitz.open(stream=pdf_bytes, filetype="pdf")
    pages: list[Image.Image] = []
    zoom = dpi / 72.0
    matrix = fitz.Matrix(zoom, zoom)
    for page in doc:
        pix = page.get_pixmap(matrix=matrix, alpha=False)
        img = Image.frombytes("RGB", (pix.width, pix.height), pix.samples)
        pages.append(img)
    doc.close()
    return pages


def preprocess(img: Image.Image) -> Image.Image:
    # Cheap, common phone-scan pipeline:
    #   grayscale -> autocontrast -> light denoise -> binarize (Otsu-ish via fixed threshold)
    # Return RGB so PaddleOCR's tensor pipeline (expects 3-channel HWC) doesn't blow up.
    g = ImageOps.grayscale(img)
    g = ImageOps.autocontrast(g, cutoff=2)
    g = g.filter(ImageFilter.MedianFilter(size=3))
    bw = g.point(lambda p: 0 if p < 160 else 255, mode="1")
    return bw.convert("RGB")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("pdf", type=Path, help="scanned-notes PDF")
    parser.add_argument("--out", type=Path, default=Path("baseline.csv"))
    parser.add_argument("--limit", type=int, default=0, help="only first N pages (0=all)")
    parser.add_argument("--skip-ocr", action="store_true", help="only time rasterize+preprocess")
    args = parser.parse_args()

    pdf_bytes = args.pdf.read_bytes()
    print(f"[fixture] {args.pdf.name} = {len(pdf_bytes)/1024:.0f} KB", flush=True)

    t0 = time.perf_counter()
    pages = rasterize(pdf_bytes)
    t_raster_total = time.perf_counter() - t0

    if args.limit:
        pages = pages[: args.limit]

    pre_images: list[Image.Image] = []
    t_pre_total = 0.0
    for img in pages:
        t = time.perf_counter()
        pre_images.append(preprocess(img))
        t_pre_total += time.perf_counter() - t

    print(f"[rasterize] {len(pages)} pages in {t_raster_total:.2f}s ({t_raster_total/len(pages)*1000:.0f} ms/page)", flush=True)
    print(f"[preprocess] {len(pre_images)} pages in {t_pre_total:.2f}s ({t_pre_total/len(pre_images)*1000:.0f} ms/page)", flush=True)

    rows: list[dict] = []
    for i, img in enumerate(pre_images):
        rows.append({
            "page": i + 1,
            "raster_ms": round((t_raster_total / len(pages)) * 1000, 1),
            "pre_ms": round((t_pre_total / len(pre_images)) * 1000, 1),
            "ocr_ms": "",
            "text_chars": "",
        })

    if args.skip_ocr:
        with args.out.open("w", newline="") as f:
            w = csv.DictWriter(f, fieldnames=["page", "raster_ms", "pre_ms", "ocr_ms", "text_chars"])
            w.writeheader()
            w.writerows(rows)
        print(f"[skip-ocr] wrote {args.out}", flush=True)
        return 0

    from paddleocr import PaddleOCR
    ocr = PaddleOCR(use_textline_orientation=True, lang="en")

    t_ocr_total = 0.0
    total_chars = 0
    for i, img in enumerate(pre_images):
        t = time.perf_counter()
        result = ocr.ocr(np.asarray(img))
        t_ocr_total += time.perf_counter() - t
        text = "\n".join(
            line[1][0]
            for page_blocks in (result or [])
            if page_blocks
            for line in page_blocks
        )
        total_chars += len(text)
        rows[i]["ocr_ms"] = round(((t_ocr_total - sum(float(r['ocr_ms'] or 0) for r in rows[:i]) / 1000)) * 1000, 1)
        # The line above is approximate; recompute cleanly:
        # We want per-page ocr_ms, not cumulative. Restart accounting:
    # Cleaner: redo OCR per page but time cleanly.
    # (PaddleOCR is stateful — re-instantiate to reset internal caches.)
    ocr = PaddleOCR(use_textline_orientation=True, lang="en")
    for i, img in enumerate(pre_images):
        t = time.perf_counter()
        result = ocr.ocr(np.asarray(img))
        ms = (time.perf_counter() - t) * 1000
        text = "\n".join(
            line[1][0]
            for page_blocks in (result or [])
            if page_blocks
            for line in page_blocks
        )
        rows[i]["ocr_ms"] = round(ms, 1)
        rows[i]["text_chars"] = len(text)

    with args.out.open("w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=["page", "raster_ms", "pre_ms", "ocr_ms", "text_chars"])
        w.writeheader()
        w.writerows(rows)

    print(f"[ocr] {len(pre_images)} pages in {t_ocr_total:.2f}s", flush=True)
    print(f"[total] {total_chars} chars recovered; csv at {args.out}", flush=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
